// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Ng6ZFwYWXD3lr_ZCpHS6iTwfihxioNk',
    appId: '1:563767744926:web:896d6f4267bf0471e31e8f',
    messagingSenderId: '563767744926',
    projectId: 'flutter-tests-b8ba6',
    authDomain: 'flutter-tests-b8ba6.firebaseapp.com',
    storageBucket: 'flutter-tests-b8ba6.appspot.com',
    measurementId: 'G-W465ELC95V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtzn29w9R-hHrSZT1cNRKPsmPDUKOxeV0',
    appId: '1:563767744926:android:558f45a6e84463f9e31e8f',
    messagingSenderId: '563767744926',
    projectId: 'flutter-tests-b8ba6',
    storageBucket: 'flutter-tests-b8ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAqVtMN2mwbKVl34gV7zJF4X6wWGYXgE',
    appId: '1:563767744926:ios:b99b2ccd51bb66fee31e8f',
    messagingSenderId: '563767744926',
    projectId: 'flutter-tests-b8ba6',
    storageBucket: 'flutter-tests-b8ba6.appspot.com',
    iosBundleId: 'com.example.flutterTestOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoAqVtMN2mwbKVl34gV7zJF4X6wWGYXgE',
    appId: '1:563767744926:ios:aa2dc61308bb9e1fe31e8f',
    messagingSenderId: '563767744926',
    projectId: 'flutter-tests-b8ba6',
    storageBucket: 'flutter-tests-b8ba6.appspot.com',
    iosBundleId: 'com.example.flutterTestOne.RunnerTests',
  );
}
